# NumPy Basics
NumPy (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers. In some ways, NumPy arrays are like Python's built-in `list` type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size. 

### Resources
- [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html)
- [NumPy Documentation](https://numpy.org/doc/stable/reference/index.html)
- [NumPy basics notes](https://gist.github.com/ShibaniOtis/666ebd044d591793f1328f90d6359e79)
- [Data types review and NumPy basics](https://github.com/richardfoltyn/python-statistics/blob/main/latex/unit02.pdf)

### Importing NumPy
Since NumPy is not part of the standard Python library, we have to import it. If it is not already installed, use pip to install it: `pip install numpy`. In the data science world, we typically import `numpy` as `np`.

In [4]:
import numpy as np

### Creating a NumPy array
NumPy arrays are very similar to built-in lists and we can create them in a very similar way.

In [5]:
list = [1,2,3,4]
np_array = np.array(list)


print(list)
print(np_array)

[1, 2, 3, 4]
[1 2 3 4]


But if we were to look at the type of both variables,

In [6]:
print(type(list))
print(type(np_array))

<class 'list'>
<class 'numpy.ndarray'>


This is pretty clunky, so we typically combine these lines.

In [18]:
np_array = np.array([1,2,3,4])
print(np_array)

[1 2 3 4]


This is exactly the same for multidimensional arrays.

In [21]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print(mat)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


There are many more ways to create specific arrays with NumPy (arrays of all 0s, arrays with random values, arrays of null values, etc.) [Array creation documentation here](https://numpy.org/doc/stable/reference/routines.array-creation.html). Those routines can be really powerful tools and we will get there, but let's stick with our simple arrays for now.

### Why NumPy arrays?

If NumPy arrays work the same as lists for the most part, then why are we even bothering with them at all?

Well, understanding how data is stored and manipulated is paramount to doing so efficiently. Since data scientists are often working with huge datasets, they are very intentional about the ways they choose to manipulate data. The differences between how Python stores data by default, in contrast to packages like NumPy or Pandas, are important nuances.

Python is a popular programming language in part because it's easy to use. One major difference between Python and other languages like C or Java is its *dynamic typing*. 

When you create a variable in Python, you can assign it a value of any data type(int, String, etc.) without having to declare the variable as a specific type. Later in your program, you can also reassign the variable to a different data type.

While this may be a valid Python program:
```python
x = 4
x = "four"
```

This same logic would cause an error in Java:
```java
int x = 4;
x = "four"; //throws Type mismatch
```

This flexibility makes Python easy to use, but also means that the Python interpreter is doing extra work behind the scenes to make this possible. Under the hood, the Python interpreter and the Python programs you create are written and compiled in C. This means everything you create in Python is really a C structure. **Variables in Python take up additional space compared to variables in both Java or C because they must store the data type, value itself, and other information.** [source](https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html)

### How are NumPy arrays different?
Just as Python variables have dynamic types, elements of lists in Python have dynamic types. 

Meaning a Python list can contain multiple types like this:
```python
list = [True, "2", 3.0, 4]
[type(item) for item in L3]
# prints [bool, str, float, int]
```

In order to do this, the underlying C compiler must account for multiple data types and stores additional information about each element. 

The fixed-type NumPy arrays lack the same flexibility, but are able to store information much more efficiently. **NumPy arrays are much more similar to Java and C arrays in their efficient implementation.**

For large projects with lots of data, these differences make a huge impact.

### Matrix vocabulary
Since NumPy is used by a lot of mathematicians and data scientists, it has a lot of built-in matrix functionality. This means the way we are going to talk about our arrays is going to be the same vocabulary we use to talk about matrices which is probably new to you!

- *row* - group data horizontally
- *column* - group data vertically
- *dimensions or shape of a matrix* - the number of rows by the number of columns
- *size of a matrix*  - the number of elements
- *scalar* - not a vector or matrix value, a number like 4 or 72
- *vector* - matrix with one column (or one row)


### About NumPy arrays
There are a few different ways we can get information about the shape of our arrays. Since we are no longer working with lists, `len()` is no longer going to work.

In [9]:
print("\nReturns a tuple with the size of each dimension")
print(mat.shape)

print("\nShow the array size")
print(mat.size)



Returns a tuple with the size of each dimension
(3, 3)

Show the array size
9


### Accessing elements
We can access elements in  NumPy arrays exactly the same way as lists. 

In [22]:
print("Get the third element of np_array")
print(mat[2])


print("\nGet the element in the second row and the third column")
print(mat[1][2]) 
#or 
print(mat[1,2])


Get the third element of np_array
[31 32 33]

Get the element in the second row and the third column
23
23


### Slicing
We haven't done too much with slicing but it can be a really powerful tool.

Some basic rules are
- We can create a slice with the format `start:stop:step`
- You can leave any those blank and it wil default to the size of the array
- The `stop` value is not inclusive!
- Any of the three values could be negative
    - If `start` or `stop` are negative, we start counting from the end of the array
    - If `step ` is negative, the order of the elements is reversed

In [33]:
print("Get the element on the first row and first and second columns")
print(mat[0][0:3:2])

Get the element on the first row and first and second columns
[11 13]


### Matrix operations
Using NumPy arrays we can easily do simple matrix operations.


**Matrix addition:** Add two arrays of the same dimensions together elementwise.

In [50]:
x = np.array([[1,6],[5,2]])
y = np.array([[5,5],[3,4]])

print(x+y)
print(x*y)
print(x/y)
print(x**y)
print(x*5)

[[ 6 11]
 [ 8  6]]
[[ 5 30]
 [15  8]]
[[0.2        1.2       ]
 [1.66666667 0.5       ]]
[[   1 7776]
 [ 125   16]]
[[ 5 30]
 [25 10]]


**Scalar multiplication:** Multiply every element in the matrix by a scalar value.

In [51]:
z = np.array([[2, 1], [1, 2]]) 

print(2*z)

[[4 2]
 [2 4]]


**Matrix multiplication:** Multiply two arrays of the same dimensions together elementwise.

In [14]:
x = np.array([[1, 0], [0, 1]])
y = np.array([[2, 1], [1, 2]]) 

print(x*y)

[[2 0]
 [0 2]]


### Creating arrays
There are a lot of different ways to easily create arrays that have some pattern to their values, whether they are all the same or only exist on the diagonal, etc.

Let's take a look at a few of them now.

In [66]:
print("Create a 1x4 array with the values 0-3")
rr = np.arange(71534765)
print(rr)

print("\nCreate a 2x2 array with zero for all values")
zmat = np.zeros((2,2))
print(zmat)


print("\nCreate a 3x3 array with one for all values")
omat = np.ones((10,10))
print(omat)


print("\nCreate a 5x2 array of 3s")
tmat = np.full((5,2),np.array(["FISH"]))
print(tmat)


print("\nCreate the identity matrix of size 4")
star = np.identity(5)
print(star)


Create a 1x4 array with the values 0-3
[       0        1        2 ... 71534762 71534763 71534764]

Create a 2x2 array with zero for all values
[[0. 0.]
 [0. 0.]]

Create a 3x3 array with one for all values
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Create a 5x2 array of 3s
[['FISH' 'FISH']
 ['FISH' 'FISH']
 ['FISH' 'FISH']
 ['FISH' 'FISH']
 ['FISH' 'FISH']]

Create the identity matrix of size 4
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Reshaping arrays
The `reshape()` function of an array can be used to reshape it into another "comfortable" shape.

In [75]:
print("Reshape a vector of 0-3 to a 2x2 matrix")
mat = np.arange(5)
print(mat)

mat = mat.reshape(5)
print(mat)


print("\nReshape it back into a vector")
vec = mat.reshape(5)
print(vec)

Reshape a vector of 0-3 to a 2x2 matrix
[0 1 2 3 4]
[0 1 2 3 4]

Reshape it back into a vector
[0 1 2 3 4]


The reshaped matrix must have the same number of elements as the original!

In [17]:
mat = np.arange(6).reshape(2,2)
print(mat)

ValueError: cannot reshape array of size 6 into shape (2,2)

# Matplitlib

In [1]:
print("Inport matplotlib")
import matplotlib.pylab as plt


print("Xreeate an array of an image")
frame = plt.imread("duck.jpg")

print("Display the image ot the terminal")
implot = plt.imshow(frame)
print(implot)

Inport matplotlib
Xreeate an array of an image


FileNotFoundError: [Errno 2] No such file or directory: 'duck.jpg'